.TH JUNZIP "1" "May 2016" "junzip 1.0" "User Commands"
.SH NAME
junzip - A fast zip file unpacker
.SH DESCRIPTION

Junzip is a very simple multithreaded zip file decompressor.

.B junzip
.I zipfile.zip

Junzip will decompress the archive into the current working directory.

.SS "options:"
.TP
There are none.
.SH SEE ALSO
https://github.com/jpakkane/jzip
