.TH PARUNZIP "1" "June 2019" "parunzip 1.3.0" "User Commands"
.SH NAME
parunzip - A fast zip file unpacker
.SH DESCRIPTION

Parunzip is a simple multithreaded zip file decompressor.

.B parunzip
.I zipfile.zip

Parunzip will decompress the archive into the current working directory.

.SS "options:"
.TP
There are none.
.SH SEE ALSO
https://github.com/jpakkane/parzip
